#!/bin/bash
#INSTALACIÓN DE APACHE

sudo apt-get update
sudo apt-get install apache2
sudo systemctl start apache2

-#INSTALAR MYSQL

sudo apt update
sudo apt-cache search mysql-server
sudo apt install mysql-server-8.0

#CREAR USUARIO Y CONTRASEÑA

sudo mysql
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'admin.123';
exit

#CONFIGURACIÓN

sudo systemctl start mysql.service
sudo mysql_secure_installation
sudo systemctl is-enabled mysql.service

#INSTALACIÓN DE PHPMYADMIN

sudo apt update
sudo apt-get install -y php php-tcpdf php-cgi php-pear php-mbstring libapache2-mod-php php-common php-phpseclib php-mysql
sudo apt install phpmyadmin php-mbstring php-zip php-gd php-json php-curl
sudo phpenmod mbstring
sudo systemctl restart apache2
